### ISSUE TITLE
Honeycomb batch response not a parseable json string (causes submission failures)

### ISSUE THREAD

**Issue by benoc617** [honeycombio/fluent-plugin-honeycomb#19]
Hello, honeycombio team!   We've just started experimenting with the fluent-plugin-honeycomb plugin and noticed an issue:

(error in the td-agent logs follows:)

2019-06-06 14:11:35 -0400 [info]: #0 publishing 363 records to dataset Fluent-test
2019-06-06 14:11:35 -0400 [warn]: #0 Error parsing response as JSON: input must be a string or IO
2019-06-06 14:11:35 -0400 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2019-06-06 14:11:36 -0400 chunk="58aaba4f416b3547fe0e0594d97de20c" error_class=JSON::ParserError error="input must be a string or IO"
  2019-06-06 14:11:35 -0400 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/yajl-ruby-1.4.1/lib/yajl/json_gem/parsing.rb:15:in `rescue in parse'
  2019-06-06 14:11:35 -0400 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/yajl-ruby-1.4.1/lib/yajl/json_gem/parsing.rb:11:in `parse'
  2019-06-06 14:11:35 -0400 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-honeycomb-0.8.0/lib/fluent/plugin/out_honeycomb.rb:141:in `parse_response'
  2019-06-06 14:11:35 -0400 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-honeycomb-0.8.0/lib/fluent/plugin/out_honeycomb.rb:125:in `publish_batch'
  2019-06-06 14:11:35 -0400 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-honeycomb-0.8.0/lib/fluent/plugin/out_honeycomb.rb:108:in `block in write'
  2019-06-06 14:11:35 -0400 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-honeycomb-0.8.0/lib/fluent/plugin/out_honeycomb.rb:107:in `each'
  2019-06-06 14:11:35 -0400 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-honeycomb-0.8.0/lib/fluent/plugin/out_honeycomb.rb:107:in `write'
  2019-06-06 14:11:35 -0400 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/compat/output.rb:131:in `write'
  2019-06-06 14:11:35 -0400 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:1125:in `try_flush'
  2019-06-06 14:11:35 -0400 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:1425:in `flush_thread_run'
  2019-06-06 14:11:35 -0400 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:454:in `block (2 levels) in start'
  2019-06-06 14:11:35 -0400 [warn]: #0 /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'

I did some (admittedly amateur) testing and fiddling, and it appears that the response body from the http post is not actually a string, but is an "HTTP::Response" object and JSON.parse can't handle it (at least in the versions of ruby and gems we have).

I was able to fix this by tweaking the response body parse operation to:
        results = JSON.parse(resp.body.to_s) 
and then rebuilding and re-installing the gem plugin.

Here's info on what versions we are running:

ruby 2.4.6
2019-06-06 12:13:39 -0400 [info]: gem 'fluent-plugin-elasticsearch' version '3.5.1'
2019-06-06 12:13:39 -0400 [info]: gem 'fluent-plugin-gelf-hs' version '1.0.8'
2019-06-06 12:13:39 -0400 [info]: gem 'fluent-plugin-honeycomb' version '0.8.0'
2019-06-06 12:13:39 -0400 [info]: gem 'fluent-plugin-kafka' version '0.9.4'
2019-06-06 12:13:39 -0400 [info]: gem 'fluent-plugin-logzio' version '0.0.19'
2019-06-06 12:13:39 -0400 [info]: gem 'fluent-plugin-prometheus' version '1.4.0'
2019-06-06 12:13:39 -0400 [info]: gem 'fluent-plugin-record-modifier' version '2.0.1'
2019-06-06 12:13:39 -0400 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.2.0'
2019-06-06 12:13:39 -0400 [info]: gem 'fluent-plugin-s3' version '1.1.10'
2019-06-06 12:13:39 -0400 [info]: gem 'fluent-plugin-td' version '1.0.0'
2019-06-06 12:13:39 -0400 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.4'
2019-06-06 12:13:39 -0400 [info]: gem 'fluent-plugin-webhdfs' version '1.2.3'
2019-06-06 12:13:39 -0400 [info]: gem 'fluentd' version '1.4.2'
*** LOCAL GEMS ***
bigdecimal (1.2.0)
io-console (0.4.2)
json (1.7.7)
psych (2.0.0)
rdoc (4.0.0)

And here is the relevant section of our config:
  <match **>
    @type honeycomb
    writekey "<omitted>"
    dataset  "Fluent-test"
  </match>

wondering if this might be a new issue due to some odd/new/old version of something we are using that is exposing this potential bug?

**Comment by JamieDanielson** [comment]
Closing this out as it looks like this was resolved with #20. Feel free to request a re-open if there's still a relevant issue.
